menu:
  about: /about
  archives: /archives
  tags: /tags

excerpt: true
feed: /atom.xml
repo: https://icylogic.net

duoshuo:

cdn:
  normalize: '//cdnjs.cloudflare.com/ajax/libs/normalize/3.0.2'
  carbon: ''
  duoshuo: '//static.duoshuo.com'
  jQuery: '//ajax.googleapis.com/ajax/libs/jquery/2.1.3'
  pjax: '//cdnjs.cloudflare.com/ajax/libs/jquery.pjax/1.9.5'
  fontawesome: '//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css'

# Custom configuration
## Twitter card header metatags
twitter_card:
  default_image:

## Google+ microdata
## See: https://developers.google.com/+/web/snippet/
## http://schema.org/Article
## http://schema.org/Blog
google_plus:
  item_type: http://schema.org/Blog
  default_image:
